module.exports = [
		{name: 'Bulbasaur', image: 'http://cdn.bulbagarden.net/upload/2/21/001Bulbasaur.png'}, // 1
		{name: 'Ivysaur', image: 'http://cdn.bulbagarden.net/upload/7/73/002Ivysaur.png'}, // 2
		{name: 'Venusaur', image: 'http://cdn.bulbagarden.net/upload/a/ae/003Venusaur.png'}, // 3
		{name: 'Charmander', image: 'http://cdn.bulbagarden.net/upload/7/73/004Charmander.png'}, // 4
		{name: 'Charmeleon', image: 'http://cdn.bulbagarden.net/upload/4/4a/005Charmeleon.png'}, // 5
		{name: 'Charizard', image: 'http://cdn.bulbagarden.net/upload/7/7e/006Charizard.png'}, // 6
		{name: 'Squirtle', image: 'http://cdn.bulbagarden.net/upload/3/39/007Squirtle.png'}, // 7
		{name: 'Wartortle', image: 'http://cdn.bulbagarden.net/upload/0/0c/008Wartortle.png'}, // 8
		{name: 'Blastoise', image: 'http://cdn.bulbagarden.net/upload/0/02/009Blastoise.png'}, // 9
		{name: 'Caterpie', image: 'http://cdn.bulbagarden.net/upload/5/5d/010Caterpie.png'}, // 10
		{name: 'Metapod', image: 'http://cdn.bulbagarden.net/upload/c/cd/011Metapod.png'}, // 11
		{name: 'Butterfree', image: 'http://cdn.bulbagarden.net/upload/d/d1/012Butterfree.png'}, // 12
		{name: 'Weedle', image: 'http://cdn.bulbagarden.net/upload/d/df/013Weedle.png'}, // 13
		{name: 'Kakuna', image: 'http://cdn.bulbagarden.net/upload/f/f0/014Kakuna.png'}, // 14
		{name: 'Beedrill', image: 'http://cdn.bulbagarden.net/upload/6/61/015Beedrill.png'}, // 15
		{name: 'Pidgey', image: 'http://cdn.bulbagarden.net/upload/5/55/016Pidgey.png'}, // 16
		{name: 'Pidgeotto', image: 'http://cdn.bulbagarden.net/upload/7/7a/017Pidgeotto.png'}, // 17
		{name: 'Pidgeot', image: 'http://cdn.bulbagarden.net/upload/5/57/018Pidgeot.png'}, // 18
		{name: 'Rattata', image: 'http://cdn.bulbagarden.net/upload/4/46/019Rattata.png'}, // 19
		{name: 'Raticate', image: 'http://cdn.bulbagarden.net/upload/f/f4/020Raticate.png'}, // 20
		{name: 'Spearow', image: 'http://cdn.bulbagarden.net/upload/8/8b/021Spearow.png'}, // 21
		{name: 'Fearow', image: 'http://cdn.bulbagarden.net/upload/a/a0/022Fearow.png'}, // 22
		{name: 'Ekans', image: 'http://cdn.bulbagarden.net/upload/f/fa/023Ekans.png'}, // 23
		{name: 'Arbok', image: 'http://cdn.bulbagarden.net/upload/c/cd/024Arbok.png'}, // 24
		{name: 'Pikachu', image: 'http://cdn.bulbagarden.net/upload/0/0d/025Pikachu.png'}, // 25
		{name: 'Raichu', image: 'http://cdn.bulbagarden.net/upload/8/88/026Raichu.png'}, // 26
		{name: 'Sandshrew', image: 'http://cdn.bulbagarden.net/upload/9/9e/027Sandshrew.png'}, // 27
		{name: 'Sandslash', image: 'http://cdn.bulbagarden.net/upload/0/0b/028Sandslash.png'}, // 28
		{name: 'Nidoran♀', image: 'http://cdn.bulbagarden.net/upload/8/81/029Nidoran.png'}, // 29
		{name: 'Nidorina', image: 'http://cdn.bulbagarden.net/upload/c/cd/030Nidorina.png'}, // 30
		{name: 'Nidoqueen', image: 'http://cdn.bulbagarden.net/upload/b/bf/031Nidoqueen.png'}, // 31
		{name: 'Nidoran♂', image: 'http://cdn.bulbagarden.net/upload/4/4a/032Nidoran.png'}, // 32
		{name: 'Nidorino', image: 'http://cdn.bulbagarden.net/upload/9/9f/033Nidorino.png'}, // 33
		{name: 'Nidoking', image: 'http://cdn.bulbagarden.net/upload/c/c6/034Nidoking.png'}, // 34
		{name: 'Clefairy', image: 'http://cdn.bulbagarden.net/upload/f/f4/035Clefairy.png'}, // 35
		{name: 'Clefable', image: 'http://cdn.bulbagarden.net/upload/a/a9/036Clefable.png'}, // 36
		{name: 'Vulpix', image: 'http://cdn.bulbagarden.net/upload/6/60/037Vulpix.png'}, // 37
		{name: 'Ninetales', image: 'http://cdn.bulbagarden.net/upload/0/05/038Ninetales.png'}, // 38
		{name: 'Jigglypuff', image: 'http://cdn.bulbagarden.net/upload/3/3e/039Jigglypuff.png'}, // 39
		{name: 'Wigglytuff', image: 'http://cdn.bulbagarden.net/upload/9/92/040Wigglytuff.png'}, // 40
		{name: 'Zubat', image: 'http://cdn.bulbagarden.net/upload/d/da/041Zubat.png'}, // 41
		{name: 'Golbat', image: 'http://cdn.bulbagarden.net/upload/0/0c/042Golbat.png'}, // 42
		{name: 'Oddish', image: 'http://cdn.bulbagarden.net/upload/4/43/043Oddish.png'}, // 43
		{name: 'Gloom', image: 'http://cdn.bulbagarden.net/upload/2/2a/044Gloom.png'}, // 44
		{name: 'Vileplume', image: 'http://cdn.bulbagarden.net/upload/6/6a/045Vileplume.png'}, // 45
		{name: 'Paras', image: 'http://cdn.bulbagarden.net/upload/d/d4/046Paras.png'}, // 46
		{name: 'Parasect', image: 'http://cdn.bulbagarden.net/upload/8/80/047Parasect.png'}, // 47
		{name: 'Venonat', image: 'http://cdn.bulbagarden.net/upload/a/ad/048Venonat.png'}, // 48
		{name: 'Venomoth', image: 'http://cdn.bulbagarden.net/upload/d/d3/049Venomoth.png'}, // 49
		{name: 'Diglett', image: 'http://cdn.bulbagarden.net/upload/3/31/050Diglett.png'}, // 50
		{name: 'Dugtrio', image: 'http://cdn.bulbagarden.net/upload/e/e5/051Dugtrio.png'}, // 51
		{name: 'Meowth', image: 'http://cdn.bulbagarden.net/upload/d/d6/052Meowth.png'}, // 52
		{name: 'Persian', image: 'http://cdn.bulbagarden.net/upload/1/13/053Persian.png'}, // 53
		{name: 'Psyduck', image: 'http://cdn.bulbagarden.net/upload/5/53/054Psyduck.png'}, // 54
		{name: 'Golduck', image: 'http://cdn.bulbagarden.net/upload/f/fe/055Golduck.png'}, // 55
		{name: 'Mankey', image: 'http://cdn.bulbagarden.net/upload/4/41/056Mankey.png'}, // 56
		{name: 'Primeape', image: 'http://cdn.bulbagarden.net/upload/9/9a/057Primeape.png'}, // 57
		{name: 'Growlithe', image: 'http://cdn.bulbagarden.net/upload/3/3d/058Growlithe.png'}, // 58
		{name: 'Arcanine', image: 'http://cdn.bulbagarden.net/upload/b/b8/059Arcanine.png'}, // 59
		{name: 'Poliwag', image: 'http://cdn.bulbagarden.net/upload/4/49/060Poliwag.png'}, // 60
		{name: 'Poliwhirl', image: 'http://cdn.bulbagarden.net/upload/a/a9/061Poliwhirl.png'}, // 61
		{name: 'Poliwrath', image: 'http://cdn.bulbagarden.net/upload/2/2d/062Poliwrath.png'}, // 62
		{name: 'Abra', image: 'http://cdn.bulbagarden.net/upload/6/62/063Abra.png'}, // 63
		{name: 'Kadabra', image: 'http://cdn.bulbagarden.net/upload/9/97/064Kadabra.png'}, // 64
		{name: 'Alakazam', image: 'http://cdn.bulbagarden.net/upload/c/cc/065Alakazam.png'}, // 65
		{name: 'Machop', image: 'http://cdn.bulbagarden.net/upload/8/85/066Machop.png'}, // 66
		{name: 'Machoke', image: 'http://cdn.bulbagarden.net/upload/8/8e/067Machoke.png'}, // 67
		{name: 'Machamp', image: 'http://cdn.bulbagarden.net/upload/8/8f/068Machamp.png'}, // 68
		{name: 'Bellsprout', image: 'http://cdn.bulbagarden.net/upload/a/a2/069Bellsprout.png'}, // 69
		{name: 'Weepinbell', image: 'http://cdn.bulbagarden.net/upload/9/9f/070Weepinbell.png'}, // 70
		{name: 'Victreebel', image: 'http://cdn.bulbagarden.net/upload/b/be/071Victreebel.png'} // 71
	]
